# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-17 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_no', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
                ('kidato', models.IntegerField()),
                ('darasa', models.CharField(max_length=1)),
                ('dob', models.DateTimeField()),
                ('kcpe_mark', models.IntegerField()),
                ('county', models.CharField(max_length=10)),
                ('year_of_completion', models.IntegerField()),
                ('parent_contact', models.CharField(max_length=10)),
            ],
        ),
    ]
